version: '3.8'
services:

  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

  database:
    image: 'postgres:15.2'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'